# Generated by Django 2.2 on 2020-04-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DadJoke_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadJokeFeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke_question', models.CharField(max_length=255)),
                ('joke_answer', models.CharField(max_length=255)),
                ('groan_factor', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dadjoke',
            name='joke_text',
        ),
        migrations.AddField(
            model_name='dadjoke',
            name='joke_answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dadjoke',
            name='joke_question',
            field=models.CharField(default='', max_length=255),
        ),
    ]
